export const TITLE = '填写退货物流'
export const TRACKING_LABEL = '快递单号'
export const TRACKING_PLACEHOLDER = '请输入快递单号'
export const BTN_SUBMIT = '提交'
export const BTN_CANCEL = '取消'
export const SHOP_RETURN_TITLE = '商家退货地址'
export const COPY = '复制'
