server:
  port: 8084

spring:
  application:
    name: logistics-service
  datasource:
    url: jdbc:mysql://localhost:3306/eureka_logistics?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 10.200.97.197:8848

mybatis:
  type-aliases-package: com.gzasc.aishopping.logistics.model
  configuration:
    map-underscore-to-camel-case: true
