events {}

http {
    include mime.types;
    default_type application/octet-stream;

    server {
        listen 80;

        location /user/ {
            alias /usr/share/nginx/html/user/;
            try_files $uri $uri/ /user/index.html;
        }

        location /seller/ {
            alias /usr/share/nginx/html/seller/;
            try_files $uri $uri/ /seller/index.html;
        }

        location /api/ {
            proxy_pass http://gateway-service:8088/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            return 301 /user/;
        }
    }
}
