export const ORDER_CARD_TEXT = {
  PRODUCT_PLACEHOLDER: '商品',
  SHOP_PLACEHOLDER: '店铺',
  QTY_LABEL: 'x',
  ORDER_DETAIL: '订单详情',
  CANCEL: '取消订单',
  PAY: '去支付',
  VIEW_LOGISTICS: '查看物流',
  CONFIRM: '确认收货',
  RETURN: '退货',
  SUBMIT_LOGISTICS: '填写退货物流',
  DELETE: '删除订单',
  ORDER_DATE: '下单时间',
  TRACKING: '物流单号',
  SHOP: '店铺',
  TIMELINE_TITLE: '订单进度',
  PROGRESS_LABEL: '已完成',
  ORDER_ID: '订单编号',
  TOTAL: '合计',
  PRODUCT_INFO: '商品信息',
  ORDER_INFO: '订单信息',
  SHOP_INFO: '店铺信息',
  DELIVERY_ADDR: '收货地址'
}
