export const AFTER_SALE_TEXT = {
  BACK: '← 返回',
  LOADING: '加载中...',
  SUBMIT_LOGISTICS: '提交物流',
  STATUS_APPLYING: '审核中',
  STATUS_AGREED: '已同意',
  STATUS_REJECTED: '已拒绝',
  RETURN_REASON: '退货理由',
  NO_RETURN_RECORD: '暂无退货记录',
  DELIVERED: '已送达',
  RETURN_PENDING: '待退货',
  RETURNING: '退货中',
  RETURNED: '已退货',
  RETURN_TRACKING: '退货物流单号',
  DETAIL_TITLE: '售后详情',
  CLOSE: '关闭',
  ORDER_ID: '订单编号',
  ORDER_STATUS: '订单状态',
  SHOP_NAME: '店铺名称',
  PRODUCT_NAME: '商品名称',
  PRODUCT_TYPE: '商品类型',
  QUANTITY: '数量',
  TOTAL_PRICE: '总价',
  RETURN_STATUS: '请求状态',
  SUBMITTED_AT: '提交时间',
  UPDATED_AT: '更新时间',
}
