server:
  port: 8085

spring:
  application:
    name: chat-service
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
    mongodb:
      uri: mongodb://localhost:27017/chat_memory_db
  cloud:
    nacos:
      discovery:
        server-addr: 10.200.97.197:8848

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

chat:
  memory:
    maxMessages: 20

app:
  file:
    storage: ${project.root:./AI-Shopping-backend}/static/file/upload
    finish: ${project.root:./AI-Shopping-backend}/static/file/finish